import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Lang = 'en' | 'sq';

const translations = {
  en: {
    // ============ COMMON ============
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    next: 'Next',
    previous: 'Previous',
    back: 'Back',
    close: 'Close',
    confirm: 'Confirm',
    search: 'Search',
    all: 'All',
    active: 'Active',
    inactive: 'Inactive',
    loading: 'Loading...',
    saving: 'Saving...',
    deleting: 'Deleting...',
    sending: 'Sending...',
    status: 'Status',
    actions: 'Actions',
    total: 'Total',
    showing: 'Showing',
    of: 'of',
    prev: 'Prev',
    email: 'Email',
    phone: 'Phone',
    name: 'Name',
    date: 'Date',
    type: 'Type',
    description: 'Description',
    customer: 'Customer',
    car: 'Car',
    amount: 'Amount',
    noDataAvailable: 'No data available',
    days: 'days',
    day: 'day',
    update: 'Update',
    create: 'Create',
    submit: 'Submit',

    // ============ NAVBAR ============
    home: 'Home',
    garage: 'Garage',
    aboutUs: 'About Us',
    blog: 'Blog',
    contact: 'Contact',
    login: 'Login',
    logout: 'Logout',
    reserveNow: 'Reserve Now',
    dashboard: 'Dashboard',
    myBookings: 'My Bookings',

    // ============ HERO ============
    premiumCarRental: 'Premium Car Rental',
    heroTitle1: 'LUXURY',
    heroTitle2: 'LIFESTYLE',
    heroTitle3: 'RENTALS',
    heroSubtitle: 'Experience premium car rental in Drenas, Kosovo. From economy to luxury, find the perfect vehicle for your journey.',
    pickupLocation: 'Pickup Location',
    pickupDate: 'Pickup Date',
    returnDate: 'Return Date',
    selectLocation: 'Select location',
    searchCars: 'Search Cars',

    // ============ FEATURED ============
    ourFleet: 'Our Fleet',
    todaysSpecials: "TODAY'S SPECIALS",
    viewAllCars: 'View All Cars',
    viewDetails: 'View Details',
    perDay: '/ Per Day',
    driveNow: 'DRIVE NOW',

    // ============ WHY US ============
    whyUs: 'Why Us',
    whyChoose: 'WHY CHOOSE NEXORA RENT A CAR',
    vehiclesAvailable: 'Vehicles Available',
    happyCustomers: 'Happy Customers',
    yearsExperience: 'Years Experience',
    customerSupport: 'Customer Support',

    // ============ CTA ============
    readyAdventure: 'Ready for Your Next Adventure?',
    ctaSubtitle: 'Book your perfect car today and explore Kosovo in style. Best prices guaranteed.',
    browseFleet: 'Browse Fleet',

    // ============ FEATURES ============
    mileageUnlimited: 'Mileage Unlimited',
    mileageDesc: 'Drive without limits — no extra charges per kilometer.',
    pickUpService: 'Pick Up Service',
    pickUpDesc: 'We deliver the car to your location in Drenas and Pristina.',
    fullInsurance: 'Full Insurance',
    insuranceDesc: 'Drive with peace of mind — comprehensive coverage included.',

    // ============ FOOTER ============
    footerDesc: 'Premium car rental service in Drenas, Kosovo. Luxury, SUV, and economy vehicles for every occasion. Trusted since 2020.',
    quickLinks: 'Quick Links',
    bookNow: 'Book Now',
    vehicleTypes: 'Vehicle Types',
    economyCars: 'Economy Cars',
    compactCars: 'Compact Cars',
    sedanCars: 'Sedan Cars',
    suvCars: 'SUV Cars',
    luxuryCars: 'Luxury Cars',
    sportsCars: 'Sports Cars',
    contactUs: 'Contact Us',
    workingHours: 'Working Hours',
    allRightsReserved: 'All rights reserved.',
    madeBy: 'Made by',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    followUs: 'FOLLOW US',

    // ============ LUXURY SECTION ============
    luxuryCarRental: 'LUXURY CAR RENTAL DRENAS',
    luxuryDesc: 'Are you looking for exotic or luxury car rental in Drenas? You want to rent a luxury car or maybe exotic car? Get in touch with Nexora Rent a Car — Exotic and Luxury Car Rental Drenas agency. Whether you need an exotic or luxury car rental for business or for pleasure.',

    // ============ ABOUT PAGE ============
    aboutHeroTitle: 'Your Trusted Car Rental Partner in Kosovo',
    aboutHeroDesc: 'Since 2020, Nexora Rent a Car has been providing premium car rental services to tourists, business travelers, and locals across Kosovo and the Balkans.',
    ourStory: 'Our Story',
    fromDrenasToKosovo: 'From Drenas to All of Kosovo',
    aboutStoryP1: 'What started as a small family business with just 3 cars has grown into one of the most trusted car rental services in the region. We take pride in offering well-maintained vehicles at competitive prices with exceptional customer service.',
    aboutStoryP2: 'Located in the heart of Drenas, we serve customers from Pristina Airport, Pristina City, Peja, and even cross-border trips to North Macedonia. Our diverse fleet ranges from fuel-efficient economy cars to premium luxury sedans and spacious SUVs.',
    vehicles: 'Vehicles',
    locations: 'Locations',
    ourValues: 'Our Values',
    whatWeStandFor: 'What We Stand For',
    reliability: 'Reliability',
    reliabilityDesc: 'Every car in our fleet is regularly maintained and inspected to ensure your safety and comfort.',
    transparency: 'Transparency',
    transparencyDesc: 'No hidden fees, no surprises. What you see is what you pay. Deposit returned in full every time.',
    serviceValue: 'Service',
    serviceDesc: 'From airport pickup to 24/7 roadside assistance, we go the extra mile for every customer.',

    // ============ CONTACT PAGE ============
    getInTouch: 'Get In Touch',
    contactSubtitle: 'Have a question or need a custom quote? Reach out to us through any of the channels below.',
    ourOffice: 'Our Office',
    sendUsMessage: 'Send us a message',
    yourName: 'Your name',
    subject: 'Subject',
    rentalInquiry: 'Rental inquiry',
    message: 'Message',
    howCanWeHelp: 'How can we help you?',
    callUs: 'Call Us',
    sendMessage: 'Send Message',
    messageSent: 'Message sent successfully!',
    messageFailed: 'Failed to send message. Please try again.',
    validPhoneError: 'Enter a valid phone number (e.g. +383 44 123 456)',

    // ============ CARS BROWSE PAGE ============
    browseOurCars: 'Browse Our Cars',
    filters: 'Filters',
    clearAll: 'Clear All',
    category: 'Category',
    fuelType: 'Fuel Type',
    transmission: 'Transmission',
    priceRange: 'Price Range (EUR/day)',
    brandOrModel: 'Brand or model...',
    min: 'Min',
    max: 'Max',
    newest: 'Newest',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    noCarsFound: 'No cars found matching your criteria.',
    clearFilters: 'Clear Filters',

    // ============ CAR DETAIL PAGE ============
    carNotFound: 'Car not found',
    backToFleet: 'Back to Fleet',
    pricePerDay: 'Price per day',
    dayShort: '/day',
    weekly: 'Weekly:',
    deposit: 'Deposit:',
    reserveThisCar: 'Reserve This Car',
    interestedInRenting: "Hi, I'm interested in renting the",
    similarCars: 'Similar Cars',
    features: 'Features',
    customerReviews: 'Customer Reviews',
    reviews: 'reviews',

    // ============ BLOG PAGE ============
    ourBlog: 'Our Blog',
    latestNewsTips: 'Latest News & Tips',
    noBlogPosts: 'No blog posts yet. Check back soon!',

    // ============ BLOG DETAIL PAGE ============
    postNotFound: 'Post Not Found',
    articleNotExist: "The article you're looking for doesn't exist.",
    backToBlog: 'Back to Blog',

    // ============ MY BOOKINGS PAGE ============
    myBookingsTitle: 'My Bookings',
    noReservationsYet: 'No reservations yet',
    browseOurFleet: 'Browse our fleet',
    cancelBookingConfirm: 'Are you sure you want to cancel this reservation?',

    // ============ LOGIN PAGE ============
    welcomeBack: 'Welcome Back',
    signInSubtitle: 'Sign in to manage your reservations',
    password: 'Password',
    signIn: 'Sign In',
    noAccount: "Don't have an account?",
    register: 'Register',
    yourPassword: 'Your password',

    // ============ REGISTER PAGE ============
    createAccount: 'Create Account',
    registerSubtitle: 'Join us for a better booking experience',
    firstName: 'First Name',
    lastName: 'Last Name',
    confirmPassword: 'Confirm Password',
    alreadyHaveAccount: 'Already have an account?',
    minCharacters: 'Min 6 characters',
    passwordsNoMatch: 'Passwords do not match',
    passwordMinLength: 'Password must be at least 6 characters',
    repeatPassword: 'Repeat password',

    // ============ RESERVE PAGE ============
    reserveYourCar: 'Reserve Your Car',
    completeSteps: 'Complete the steps below to book your vehicle.',
    datesAndLocation: 'Dates & Location',
    chooseCar: 'Choose Car',
    extras: 'Extras',
    yourDetailsStep: 'Your Details',
    confirmStep: 'Confirm',
    selectDatesLocation: 'Select Dates & Location',
    dropoffLocation: 'Dropoff Location',
    pickupTime: 'Pickup Time',
    returnTime: 'Return Time',
    chooseYourCar: 'Choose Your Car',
    selectExtras: 'Select Extras',
    loggedInDetails: 'Logged in - details will be used automatically',
    loginForFaster: 'for a faster checkout, or continue as guest:',
    fullName: 'Full Name',
    yourFullName: 'Your full name',
    notesOptional: 'Notes (optional)',
    specialRequests: 'Any special requests...',
    reviewReservation: 'Review Your Reservation',
    pickup: 'Pickup',
    returnLabel: 'Return',
    duration: 'Duration',
    dailyRate: 'Daily Rate',
    baseDays: 'Base',
    reservationConfirmed: 'Reservation Confirmed!',
    reservationNumberIs: 'Your reservation number is:',
    contactSoon: "We'll contact you shortly to confirm the details. Check your email for the receipt.",
    backToHome: 'Back to Home',
    whatsappUs: 'WhatsApp Us',
    confirmReservation: 'Confirm Reservation',
    failedCreateReservation: 'Failed to create reservation',
    at: 'at',

    // ============ NOT FOUND PAGE ============
    pageNotFound: 'Page Not Found',
    pageNotFoundDesc: "The page you're looking for doesn't exist or has been moved.",
    goHome: 'Go Home',
    browseCars: 'Browse Cars',

    // ============ CAR CARD ============
    available: 'Available',
    booked: 'Booked',
    viewDetailsArrow: 'View Details \u2192',

    // ============ ADMIN LAYOUT ============
    adminDashboardLabel: 'Dashboard',
    adminCarsLabel: 'Cars',
    adminReservationsLabel: 'Reservations',
    adminCustomersLabel: 'Customers',
    adminRevenueLabel: 'Revenue',
    adminReviewsLabel: 'Reviews',
    adminExpensesLabel: 'Expenses',
    adminMaintenanceLabel: 'Maintenance',
    adminPricingLabel: 'Pricing',
    adminLoyaltyLabel: 'Loyalty',
    adminNotificationsLabel: 'Notifications',
    adminDeliveriesLabel: 'Deliveries',
    adminBlogLabel: 'Blog',
    adminMessagesLabel: 'Messages',
    adminSettingsLabel: 'Settings',
    collapse: 'Collapse',

    // ============ ADMIN DASHBOARD ============
    revenueThisMonth: 'Revenue This Month',
    activeReservations: 'Active Reservations',
    availableCarsLabel: 'Available Cars',
    newCustomers: 'New Customers',
    revenueOverview: 'Revenue Overview',
    noRevenueData: 'No revenue data yet',
    bookingStatus: 'Booking Status',
    noBookingsYet: 'No bookings yet',
    recentReservations: 'Recent Reservations',
    noReservationsYetAdmin: 'No reservations yet',
    dates: 'Dates',

    // ============ ADMIN CARS ============
    addNewCar: 'Add New Car',
    searchCarsPlaceholder: 'Search cars...',
    allCategories: 'All Categories',
    image: 'Image',
    brandModel: 'Brand / Model',
    priceDay: 'Price/Day',
    noImg: 'No img',

    // ============ ADMIN RESERVATIONS ============
    newReservation: 'New Reservation',
    calendarView: 'Calendar View',
    pending: 'Pending',
    confirmed: 'Confirmed',
    completed: 'Completed',
    cancelled: 'Cancelled',
    rejected: 'Rejected',
    searchReservationsPlaceholder: 'Search by reservation #, customer name...',
    noReservationsFound: 'No reservations found',
    reservation: 'Reservation',
    updateStatus: 'Update Status',
    markActive: 'Mark Active',
    markCompleted: 'Mark Completed',
    reject: 'Reject',
    extendReservation: 'Extend Reservation',
    daysToAdd: 'Days to add',
    addDays: 'Add Days',
    extending: 'Extending...',
    newTotal: 'New total:',
    downloadInvoice: 'Download Invoice PDF',
    customerNotes: 'Customer Notes',
    subtotal: 'Subtotal',
    discount: 'Discount',
    to: 'to',

    // ============ ADMIN CUSTOMERS ============
    customersTitle: 'Customers',
    searchCustomersPlaceholder: 'Search customers...',
    noCustomersFound: 'No customers found',
    bookings: 'Bookings',
    totalSpent: 'Total Spent',
    lastBooking: 'Last Booking',
    memberSince: 'Member Since',
    rentalHistory: 'Rental History',
    noRentalsYet: 'No rentals yet',

    // ============ ADMIN REVENUE ============
    revenue: 'Revenue',
    days7: '7 Days',
    days30: '30 Days',
    days90: '90 Days',
    months12: '12 Months',
    totalRevenue: 'Total Revenue',
    totalBookings: 'Total Bookings',
    avgBookingValue: 'Avg. Booking Value',
    avgRentalDays: 'Avg. Rental Days',
    revenueOverTime: 'Revenue Over Time',
    noDataPeriod: 'No data for this period',
    revenueByCategory: 'Revenue by Category',
    topPerformingCars: 'Top Performing Cars',

    // ============ ADMIN BLOG ============
    blogPosts: 'Blog Posts',
    newPost: 'New Post',
    title: 'Title',
    excerpt: 'Excerpt',
    content: 'Content',
    publishImmediately: 'Publish immediately',
    editPost: 'Edit Post',
    created: 'Created',

    // ============ ADMIN MESSAGES ============
    messages: 'Messages',
    noMessagesYet: 'No messages yet',
    noSubject: 'No subject',
    from: 'From',
    replyViaEmail: 'Reply via Email',

    // ============ ADMIN SETTINGS ============
    settings: 'Settings',
    saveChanges: 'Save Changes',
    saved: 'Saved',
    companyInfo: 'Company Information',
    companyName: 'Company Name',
    whatsappNumber: 'WhatsApp Number',
    address: 'Address',
    city: 'City',
    workingHoursTitle: 'Working Hours',
    weekdays: 'Weekdays (Mon-Fri)',
    weekends: 'Weekends (Sat-Sun)',
    socialMedia: 'Social Media',
    facebookUrl: 'Facebook URL',
    instagramUrl: 'Instagram URL',
    tiktokUrl: 'TikTok URL',

    // ============ ADMIN REVIEWS ============
    reviewsTitle: 'Reviews',
    totalReviews: 'Total Reviews',
    approved: 'Approved',
    rating: 'Rating',
    comment: 'Comment',
    reviewDetails: 'Review Details',
    adminReply: 'Admin Reply',
    repliedOn: 'Replied on',
    approve: 'Approve',
    reply: 'Reply',
    editReply: 'Edit Reply',
    deleteReview: 'Delete Review',
    deleteReviewConfirm: 'Are you sure you want to delete this review? This action cannot be undone.',
    replyToReview: 'Reply to Review',
    yourReply: 'Your Reply',
    writeReply: 'Write your reply to this review...',
    sendReply: 'Send Reply',

    // ============ ADMIN EXPENSES ============
    expenseTracking: 'Expense Tracking',
    totalExpenses: 'Total expenses:',
    addExpense: 'Add Expense',
    allExpenses: 'All Expenses',
    profitabilitySummary: 'Profitability Summary',
    noExpensesFound: 'No expenses found',
    profitabilityNoData: 'No profitability data available',
    expenses: 'Expenses',
    profit: 'Profit',
    profitable: 'Profitable',
    loss: 'Loss',
    editExpense: 'Edit Expense',
    selectCar: 'Select a car',
    briefDescription: 'Brief description...',
    expenseDate: 'Expense Date',
    vendor: 'Vendor',
    vendorName: 'Vendor name',
    receiptUrl: 'Receipt URL',
    updateExpense: 'Update Expense',
    deleteExpense: 'Delete Expense',
    deleteExpenseConfirm: 'Are you sure you want to delete this expense? This action cannot be undone.',

    // ============ ADMIN MAINTENANCE ============
    maintenanceTitle: 'Maintenance Scheduler',
    newRecord: 'New Record',
    alerts: 'Alerts',
    records: 'Records',
    types: 'Types',
    scheduled: 'Scheduled',
    inProgress: 'In Progress',
    overdue: 'Overdue',
    scheduledDate: 'Scheduled Date',
    cost: 'Cost',
    markComplete: 'Mark Complete',

    // ============ ADMIN PRICING ============
    dynamicPricing: 'Dynamic Pricing',
    lowDemand: 'Low Demand',
    mediumDemand: 'Medium Demand',
    highDemand: 'High Demand',
    veryHighDemand: 'Very High Demand',
    demand: 'Demand',
    advanceBooking: 'Advance Booking',
    durationLabel: 'Duration',
    lastMinute: 'Last Minute',
    event: 'Event',
    addRule: 'Add Rule',
    demandOverview: 'Demand Overview',
    currentDemand: 'Current Demand',
    totalCarsCount: 'Total Cars',
    pricingRules: 'Pricing Rules',
    noPricingRules: 'No pricing rules configured yet.',
    createFirstRule: 'Create First Rule',
    priority: 'Priority',
    conditions: 'Conditions',
    priceCalculator: 'Price Calculator',
    selectCarLabel: 'Select car',
    calculatePrice: 'Calculate Price',
    seasonalMultiplier: 'Seasonal Multiplier',
    dynamicMultiplier: 'Dynamic Multiplier',
    finalDailyRate: 'Final Daily Rate',
    totalDays: 'Total Days',
    totalPrice: 'Total Price',
    appliedRules: 'Applied Rules',

    // ============ ADMIN LOYALTY ============
    loyaltyProgram: 'Loyalty Program',
    totalMembers: 'Total Members',
    pointsIssued: 'Points Issued',
    bronze: 'Bronze',
    silver: 'Silver',
    gold: 'Gold',
    platinum: 'Platinum',
    members: 'Members',
    rewardsLabel: 'Rewards',
    pointsBalance: 'Points Balance',
    lifetimePoints: 'Lifetime Points',
    newReward: 'New Reward',
    rewardName: 'Reward Name',
    rewardType: 'Reward Type',
    discountPercent: 'Discount %',
    fixedDiscount: 'Fixed Discount',
    freeDay: 'Free Day',
    upgrade: 'Upgrade',
    freeExtra: 'Free Extra',
    pointsCost: 'Points Cost',
    minimumTier: 'Minimum Tier',
    adjustPoints: 'Adjust Points',
    addPoints: 'Add Points',
    bonus: 'Bonus',
    adjust: 'Adjust',
    expire: 'Expire',
    redeemReward: 'Redeem Reward',
    selectReward: 'Select Reward',
    redeem: 'Redeem',
    pointsPerEuro: 'Points per Euro',
    tierThresholds: 'Tier Thresholds',
    saveSettings: 'Save Settings',

    // ============ ADMIN NOTIFICATIONS ============
    whatsappNotifications: 'WhatsApp Notifications',
    totalSent: 'Total Sent',
    delivered: 'Delivered',
    failed: 'Failed',
    notificationLog: 'Notification Log',
    templates: 'Templates',
    sendManual: 'Send Manual',
    recipient: 'Recipient',
    reservationNum: 'Reservation #',
    sentAt: 'Sent At',
    noNotificationsFound: 'No notifications found',
    noTemplatesFound: 'No templates found',
    editTemplate: 'Edit Template',
    templateName: 'Template Name',
    templateBody: 'Template Body',
    availableVariables: 'Available Variables',
    sendWhatsappNotification: 'Send WhatsApp Notification',
    phoneNumber: 'Phone Number',
    notificationType: 'Notification Type',
    reservationId: 'Reservation ID',
    optional: '(optional)',
    sendNotification: 'Send Notification',
    openWhatsapp: 'Open WhatsApp',

    // ============ ADMIN DELIVERIES ============
    deliveryTracking: 'Delivery Tracking',
    assigned: 'Assigned',
    enRoute: 'En Route',
    arrived: 'Arrived',
    driver: 'Driver',
    delivery: 'Delivery',
    returnPickup: 'Return Pickup',
    destination: 'Destination',
    noDeliveriesFound: 'No deliveries found',
    newDelivery: 'New Delivery',
    chatOnWhatsapp: 'Chat on WhatsApp',
    activeDeliveries: 'active delivery/deliveries',
    createDelivery: 'Create Delivery',
    deliveryDetails: 'Delivery Details',
    locationHistory: 'Location History',
    noLocationData: 'No location data available yet.',
    loadingLocationsText: 'Loading locations...',
    reservationIdLabel: 'Reservation ID',
    enterReservationId: 'Enter reservation ID',
    selectADriver: 'Select a driver',
    destinationAddress: 'Destination Address',
    fullDeliveryAddress: 'Full delivery address',
    latitude: 'Latitude',
    longitude: 'Longitude',
    specialInstructions: 'Any special instructions...',
    notesLabel: 'Notes',
    started: 'Started',

    // ============ ADMIN NEW RESERVATION ============
    newReservationTitle: 'New Reservation',
    fillRequiredFields: 'Please fill in all required fields',
    fixPhoneNumber: 'Please fix the phone number',
    creating: 'Creating...',
    createReservationInvoice: 'Create Reservation & Generate Invoice',
    customerDetails: 'Customer Details',
    vehicleLabel: 'Vehicle',
    datesLocations: 'Dates & Locations',
    notesStatus: 'Notes & Status',
    adminNotesLabel: 'Admin Notes',
    internalNotes: 'Internal notes...',
    initialStatus: 'Initial Status',
    priceSummary: 'Price Summary',

    // ============ ADMIN CALENDAR ============
    reservationCalendar: 'Reservation Calendar',
    week: 'Week',
    month: 'Month',
    noReservationsDisplay: 'No reservations to display',

    // ============ CAR FORM ============
    details: 'Details',
    pricing: 'Pricing',
    imagesTab: 'Images',
    featuresTab: 'Features',
    brand: 'Brand',
    model: 'Model',
    year: 'Year',
    economy: 'Economy',
    compact: 'Compact',
    sedan: 'Sedan',
    suv: 'SUV',
    luxury: 'Luxury',
    van: 'Van',
    sports: 'Sports',
    petrol: 'Petrol',
    diesel: 'Diesel',
    hybrid: 'Hybrid',
    electric: 'Electric',
    manual: 'Manual',
    automatic: 'Automatic',
    seats: 'Seats',
    doors: 'Doors',
    horsepower: 'Horsepower',
    engineCC: 'Engine CC',
    color: 'Color',
    licensePlate: 'License Plate',
    mileageKm: 'Mileage (km)',
    pricePerDayEur: 'Price Per Day (EUR)',
    pricePerWeekEur: 'Price Per Week (EUR)',
    depositEur: 'Deposit (EUR)',
    featuredCar: 'Featured car (shown on homepage)',
    saveCarFirst: 'Save the car first, then you can add images.',
    addImageUrl: 'Add Image URL',
    addImage: 'Add Image',
    adding: 'Adding...',
    pasteImageUrl: 'Paste any image URL. The first image will be set as the primary/cover image.',
    primaryImage: 'Primary',
    noImagesYet: 'No images yet. Add one above.',
    setAsPrimary: 'Set as primary',
    selectFeatures: 'Select the features this car has:',
    gps: 'GPS',
    airConditioning: 'Air Conditioning',
    bluetooth: 'Bluetooth',
    usb: 'USB',
    cruiseControl: 'Cruise Control',
    parkingSensors: 'Parking Sensors',
    backupCamera: 'Backup Camera',
    heatedSeats: 'Heated Seats',
    leatherSeats: 'Leather Seats',
    sunroof: 'Sunroof',
    appleCarplay: 'Apple CarPlay',
    androidAuto: 'Android Auto',
    keylessEntry: 'Keyless Entry',
    abs: 'ABS',
    airbags: 'Airbags',
    updateCar: 'Update Car',
    createCar: 'Create Car',
    addNewCarTitle: 'Add New Car',
    editCarTitle: 'Edit Car',
  },
  sq: {
    // ============ COMMON ============
    cancel: 'Anulo',
    save: 'Ruaj',
    delete: 'Fshi',
    edit: 'Ndrysho',
    view: 'Shiko',
    next: 'Tjetri',
    previous: 'Mëparshmi',
    back: 'Kthehu',
    close: 'Mbyll',
    confirm: 'Konfirmo',
    search: 'Kërko',
    all: 'Të gjitha',
    active: 'Aktive',
    inactive: 'Joaktive',
    loading: 'Duke u ngarkuar...',
    saving: 'Duke u ruajtur...',
    deleting: 'Duke u fshirë...',
    sending: 'Duke u dërguar...',
    status: 'Statusi',
    actions: 'Veprimet',
    total: 'Totali',
    showing: 'Duke treguar',
    of: 'nga',
    prev: 'Para',
    email: 'Email',
    phone: 'Telefoni',
    name: 'Emri',
    date: 'Data',
    type: 'Lloji',
    description: 'Përshkrimi',
    customer: 'Klienti',
    car: 'Makina',
    amount: 'Shuma',
    noDataAvailable: 'Nuk ka të dhëna',
    days: 'ditë',
    day: 'ditë',
    update: 'Përditëso',
    create: 'Krijo',
    submit: 'Dërgo',

    // ============ NAVBAR ============
    home: 'Ballina',
    garage: 'Garazhi',
    aboutUs: 'Rreth Nesh',
    blog: 'Blog',
    contact: 'Kontakti',
    login: 'Hyr',
    logout: 'Dil',
    reserveNow: 'Rezervo Tani',
    dashboard: 'Paneli',
    myBookings: 'Rezervimet e Mia',

    // ============ HERO ============
    premiumCarRental: 'Qiradhënie Premium e Makinave',
    heroTitle1: 'LUKSI',
    heroTitle2: 'STILI I',
    heroTitle3: 'JETESËS',
    heroSubtitle: 'Përjetoni qiradhënien premium të makinave në Drenas, Kosovë. Nga ekonomike deri te luksoze, gjeni automjetin perfekt për udhëtimin tuaj.',
    pickupLocation: 'Vendndodhja e Marrjes',
    pickupDate: 'Data e Marrjes',
    returnDate: 'Data e Kthimit',
    selectLocation: 'Zgjidhni vendndodhjen',
    searchCars: 'Kërko Makina',

    // ============ FEATURED ============
    ourFleet: 'Flota Jonë',
    todaysSpecials: 'OFERTAT E DITËS',
    viewAllCars: 'Shiko të Gjitha Makinat',
    viewDetails: 'Shiko Detajet',
    perDay: '/ Për Ditë',
    driveNow: 'VOZIT TANI',

    // ============ WHY US ============
    whyUs: 'Pse Ne',
    whyChoose: 'PSE TË ZGJIDHNI NEXORA RENT A CAR',
    vehiclesAvailable: 'Automjete në Dispozicion',
    happyCustomers: 'Klientë të Kënaqur',
    yearsExperience: 'Vite Përvojë',
    customerSupport: 'Mbështetje për Klientët',

    // ============ CTA ============
    readyAdventure: 'Gati për Aventurën Tjetër?',
    ctaSubtitle: 'Rezervoni makinën tuaj perfekte sot dhe eksploroni Kosovën me stil. Çmimet më të mira të garantuara.',
    browseFleet: 'Shfleto Flotën',

    // ============ FEATURES ============
    mileageUnlimited: 'Kilometrazh i Pakufizuar',
    mileageDesc: 'Vozitni pa kufij — pa tarifa shtesë për kilometër.',
    pickUpService: 'Shërbim Marrjeje',
    pickUpDesc: 'Ua dorëzojmë makinën në vendndodhjen tuaj në Drenas dhe Prishtinë.',
    fullInsurance: 'Sigurim i Plotë',
    insuranceDesc: 'Vozitni me qetësi — mbulim gjithëpërfshirës i përfshirë.',

    // ============ FOOTER ============
    footerDesc: 'Shërbim premium i qiradhënies së makinave në Drenas, Kosovë. Makina luksoze, SUV dhe ekonomike për çdo rast. Të besuar që nga 2020.',
    quickLinks: 'Lidhje të Shpejta',
    bookNow: 'Rezervo Tani',
    vehicleTypes: 'Llojet e Automjeteve',
    economyCars: 'Makina Ekonomike',
    compactCars: 'Makina Kompakte',
    sedanCars: 'Makina Sedan',
    suvCars: 'Makina SUV',
    luxuryCars: 'Makina Luksoze',
    sportsCars: 'Makina Sportive',
    contactUs: 'Na Kontaktoni',
    workingHours: 'Orari i Punës',
    allRightsReserved: 'Të gjitha të drejtat e rezervuara.',
    madeBy: 'Krijuar nga',
    privacyPolicy: 'Politika e Privatësisë',
    termsOfService: 'Kushtet e Shërbimit',
    followUs: 'NA NDIQNI',

    // ============ LUXURY SECTION ============
    luxuryCarRental: 'QIRADHËNIA E MAKINAVE LUKSOZE DRENAS',
    luxuryDesc: 'A jeni duke kërkuar qiradhënie të makinave ekzotike ose luksoze në Drenas? Dëshironi të merrni me qira një makinë luksoze apo ndoshta ekzotike? Kontaktoni Nexora Rent a Car — Agjencia e qiradhënies së makinave ekzotike dhe luksoze në Drenas. Qoftë për biznes apo për kënaqësi.',

    // ============ ABOUT PAGE ============
    aboutHeroTitle: 'Partneri Juaj i Besuar për Qiradhënie Makinash në Kosovë',
    aboutHeroDesc: 'Që nga viti 2020, Nexora Rent a Car ka ofruar shërbime premium të qiradhënies së makinave për turistë, udhëtarë biznesi dhe vendas në të gjithë Kosovën dhe Ballkanin.',
    ourStory: 'Historia Jonë',
    fromDrenasToKosovo: 'Nga Drenasi në Mbarë Kosovën',
    aboutStoryP1: 'Ajo që filloi si një biznes i vogël familjar me vetëm 3 makina, është rritur në një nga shërbimet më të besuara të qiradhënies së makinave në rajon. Ne krenohem duke ofruar automjete të mirëmbajtura me çmime konkurruese dhe shërbim të jashtëzakonshëm ndaj klientëve.',
    aboutStoryP2: 'E vendosur në zemër të Drenasit, ne u shërbejmë klientëve nga Aeroporti i Prishtinës, qyteti i Prishtinës, Peja, madje edhe udhëtime ndërkufitare në Maqedoninë e Veriut. Flota jonë e larmishme përfshin makina ekonomike me efikasitet të lartë deri te sedanë premium luksoze dhe SUV të gjera.',
    vehicles: 'Automjete',
    locations: 'Vendndodhje',
    ourValues: 'Vlerat Tona',
    whatWeStandFor: 'Për Çfarë Qëndrojmë',
    reliability: 'Besueshmëria',
    reliabilityDesc: 'Çdo makinë në flotën tonë mirëmbahet dhe kontrollohet rregullisht për të siguruar sigurinë dhe komoditetin tuaj.',
    transparency: 'Transparenca',
    transparencyDesc: 'Pa tarifa të fshehura, pa surpriza. Atë që shihni, atë paguani. Depozita kthehet e plotë çdo herë.',
    serviceValue: 'Shërbimi',
    serviceDesc: 'Nga marrja në aeroport deri te ndihma rrugore 24/7, ne bëjmë më shumë se duhet për çdo klient.',

    // ============ CONTACT PAGE ============
    getInTouch: 'Na Kontaktoni',
    contactSubtitle: 'Keni pyetje ose keni nevojë për një ofertë të personalizuar? Na kontaktoni përmes kanaleve më poshtë.',
    ourOffice: 'Zyra Jonë',
    sendUsMessage: 'Na dërgoni një mesazh',
    yourName: 'Emri juaj',
    subject: 'Subjekti',
    rentalInquiry: 'Pyetje për qiradhënie',
    message: 'Mesazhi',
    howCanWeHelp: 'Si mund t\'ju ndihmojmë?',
    callUs: 'Na Telefononi',
    sendMessage: 'Dërgo Mesazhin',
    messageSent: 'Mesazhi u dërgua me sukses!',
    messageFailed: 'Dërgimi i mesazhit dështoi. Ju lutem provoni përsëri.',
    validPhoneError: 'Vendosni numër telefoni valid (p.sh. +383 44 123 456)',

    // ============ CARS BROWSE PAGE ============
    browseOurCars: 'Shfleto Makinat Tona',
    filters: 'Filtrat',
    clearAll: 'Pastro të Gjitha',
    category: 'Kategoria',
    fuelType: 'Lloji i Karburantit',
    transmission: 'Transmisioni',
    priceRange: 'Diapazoni i Çmimit (EUR/ditë)',
    brandOrModel: 'Marka ose modeli...',
    min: 'Min',
    max: 'Maks',
    newest: 'Më të rejat',
    priceLowHigh: 'Çmimi: Nga më i ulëti',
    priceHighLow: 'Çmimi: Nga më i larti',
    noCarsFound: 'Nuk u gjetën makina sipas kritereve tuaja.',
    clearFilters: 'Pastro Filtrat',

    // ============ CAR DETAIL PAGE ============
    carNotFound: 'Makina nuk u gjet',
    backToFleet: 'Kthehu te Flota',
    pricePerDay: 'Çmimi për ditë',
    dayShort: '/ditë',
    weekly: 'Javore:',
    deposit: 'Depozita:',
    reserveThisCar: 'Rezervo Këtë Makinë',
    interestedInRenting: 'Përshëndetje, jam i interesuar për qiradhënien e',
    similarCars: 'Makina të Ngjashme',
    features: 'Veçoritë',
    customerReviews: 'Vlerësimet e Klientëve',
    reviews: 'vlerësime',

    // ============ BLOG PAGE ============
    ourBlog: 'Blogu Ynë',
    latestNewsTips: 'Lajmet dhe Këshillat e Fundit',
    noBlogPosts: 'Nuk ka postime në blog ende. Kontrolloni përsëri së shpejti!',

    // ============ BLOG DETAIL PAGE ============
    postNotFound: 'Postimi Nuk u Gjet',
    articleNotExist: 'Artikulli që po kërkoni nuk ekziston.',
    backToBlog: 'Kthehu te Blogu',

    // ============ MY BOOKINGS PAGE ============
    myBookingsTitle: 'Rezervimet e Mia',
    noReservationsYet: 'Nuk ka rezervime ende',
    browseOurFleet: 'Shfleto flotën tonë',
    cancelBookingConfirm: 'A jeni i sigurt që dëshironi të anuloni këtë rezervim?',

    // ============ LOGIN PAGE ============
    welcomeBack: 'Mirë se Erdhët Përsëri',
    signInSubtitle: 'Hyni për të menaxhuar rezervimet tuaja',
    password: 'Fjalëkalimi',
    signIn: 'Hyr',
    noAccount: 'Nuk keni llogari?',
    register: 'Regjistrohu',
    yourPassword: 'Fjalëkalimi juaj',

    // ============ REGISTER PAGE ============
    createAccount: 'Krijo Llogari',
    registerSubtitle: 'Bashkohuni me ne për një përvojë më të mirë rezervimi',
    firstName: 'Emri',
    lastName: 'Mbiemri',
    confirmPassword: 'Konfirmo Fjalëkalimin',
    alreadyHaveAccount: 'Keni tashmë një llogari?',
    minCharacters: 'Min 6 karaktere',
    passwordsNoMatch: 'Fjalëkalimet nuk përputhen',
    passwordMinLength: 'Fjalëkalimi duhet të ketë të paktën 6 karaktere',
    repeatPassword: 'Përsërit fjalëkalimin',

    // ============ RESERVE PAGE ============
    reserveYourCar: 'Rezervoni Makinën Tuaj',
    completeSteps: 'Plotësoni hapat më poshtë për të rezervuar automjetin tuaj.',
    datesAndLocation: 'Data dhe Vendndodhja',
    chooseCar: 'Zgjidhni Makinën',
    extras: 'Shtesa',
    yourDetailsStep: 'Të Dhënat Tuaja',
    confirmStep: 'Konfirmo',
    selectDatesLocation: 'Zgjidhni Datat dhe Vendndodhjen',
    dropoffLocation: 'Vendndodhja e Dorëzimit',
    pickupTime: 'Ora e Marrjes',
    returnTime: 'Ora e Kthimit',
    chooseYourCar: 'Zgjidhni Makinën Tuaj',
    selectExtras: 'Zgjidhni Shtesat',
    loggedInDetails: 'I kyçur - të dhënat do të përdoren automatikisht',
    loginForFaster: 'për pagesë më të shpejtë, ose vazhdoni si mysafir:',
    fullName: 'Emri i Plotë',
    yourFullName: 'Emri juaj i plotë',
    notesOptional: 'Shënime (opsionale)',
    specialRequests: 'Kërkesa të veçanta...',
    reviewReservation: 'Rishikoni Rezervimin Tuaj',
    pickup: 'Marrja',
    returnLabel: 'Kthimi',
    duration: 'Kohëzgjatja',
    dailyRate: 'Tarifa Ditore',
    baseDays: 'Baza',
    reservationConfirmed: 'Rezervimi u Konfirmua!',
    reservationNumberIs: 'Numri i rezervimit tuaj është:',
    contactSoon: 'Do t\'ju kontaktojmë së shpejti për të konfirmuar detajet. Kontrolloni emailin tuaj për faturën.',
    backToHome: 'Kthehu në Ballina',
    whatsappUs: 'Na Shkruani në WhatsApp',
    confirmReservation: 'Konfirmo Rezervimin',
    failedCreateReservation: 'Krijimi i rezervimit dështoi',
    at: 'në',

    // ============ NOT FOUND PAGE ============
    pageNotFound: 'Faqja Nuk u Gjet',
    pageNotFoundDesc: 'Faqja që po kërkoni nuk ekziston ose është lëvizur.',
    goHome: 'Shko në Ballina',
    browseCars: 'Shfleto Makinat',

    // ============ CAR CARD ============
    available: 'E Disponueshme',
    booked: 'E Rezervuar',
    viewDetailsArrow: 'Shiko Detajet \u2192',

    // ============ ADMIN LAYOUT ============
    adminDashboardLabel: 'Paneli',
    adminCarsLabel: 'Makinat',
    adminReservationsLabel: 'Rezervimet',
    adminCustomersLabel: 'Klientët',
    adminRevenueLabel: 'Të Ardhurat',
    adminReviewsLabel: 'Vlerësimet',
    adminExpensesLabel: 'Shpenzimet',
    adminMaintenanceLabel: 'Mirëmbajtja',
    adminPricingLabel: 'Çmimet',
    adminLoyaltyLabel: 'Besnikëria',
    adminNotificationsLabel: 'Njoftimet',
    adminDeliveriesLabel: 'Dërgesat',
    adminBlogLabel: 'Blogu',
    adminMessagesLabel: 'Mesazhet',
    adminSettingsLabel: 'Cilësimet',
    collapse: 'Mbyll',

    // ============ ADMIN DASHBOARD ============
    revenueThisMonth: 'Të Ardhurat Këtë Muaj',
    activeReservations: 'Rezervime Aktive',
    availableCarsLabel: 'Makina të Disponueshme',
    newCustomers: 'Klientë të Rinj',
    revenueOverview: 'Pasqyra e të Ardhurave',
    noRevenueData: 'Nuk ka të dhëna për të ardhurat ende',
    bookingStatus: 'Statusi i Rezervimeve',
    noBookingsYet: 'Nuk ka rezervime ende',
    recentReservations: 'Rezervimet e Fundit',
    noReservationsYetAdmin: 'Nuk ka rezervime ende',
    dates: 'Datat',

    // ============ ADMIN CARS ============
    addNewCar: 'Shto Makinë të Re',
    searchCarsPlaceholder: 'Kërko makina...',
    allCategories: 'Të Gjitha Kategoritë',
    image: 'Foto',
    brandModel: 'Marka / Modeli',
    priceDay: 'Çmimi/Ditë',
    noImg: 'Pa foto',

    // ============ ADMIN RESERVATIONS ============
    newReservation: 'Rezervim i Ri',
    calendarView: 'Pamja Kalendarike',
    pending: 'Në Pritje',
    confirmed: 'E Konfirmuar',
    completed: 'E Përfunduar',
    cancelled: 'E Anuluar',
    rejected: 'E Refuzuar',
    searchReservationsPlaceholder: 'Kërko me nr. rezervimit, emrin e klientit...',
    noReservationsFound: 'Nuk u gjetën rezervime',
    reservation: 'Rezervimi',
    updateStatus: 'Përditëso Statusin',
    markActive: 'Shëno Aktive',
    markCompleted: 'Shëno të Përfunduar',
    reject: 'Refuzo',
    extendReservation: 'Zgjat Rezervimin',
    daysToAdd: 'Ditë për të shtuar',
    addDays: 'Shto Ditë',
    extending: 'Duke u zgjatur...',
    newTotal: 'Totali i ri:',
    downloadInvoice: 'Shkarko Faturën PDF',
    customerNotes: 'Shënimet e Klientit',
    subtotal: 'Nëntotali',
    discount: 'Zbritja',
    to: 'deri',

    // ============ ADMIN CUSTOMERS ============
    customersTitle: 'Klientët',
    searchCustomersPlaceholder: 'Kërko klientë...',
    noCustomersFound: 'Nuk u gjetën klientë',
    bookings: 'Rezervimet',
    totalSpent: 'Totali i Shpenzuar',
    lastBooking: 'Rezervimi i Fundit',
    memberSince: 'Anëtar Që Nga',
    rentalHistory: 'Historiku i Qiradhënieve',
    noRentalsYet: 'Nuk ka qiradhënie ende',

    // ============ ADMIN REVENUE ============
    revenue: 'Të Ardhurat',
    days7: '7 Ditë',
    days30: '30 Ditë',
    days90: '90 Ditë',
    months12: '12 Muaj',
    totalRevenue: 'Të Ardhurat Totale',
    totalBookings: 'Rezervime Totale',
    avgBookingValue: 'Vlera Mesatare e Rezervimit',
    avgRentalDays: 'Ditët Mesatare të Qiradhënies',
    revenueOverTime: 'Të Ardhurat me Kalimin e Kohës',
    noDataPeriod: 'Nuk ka të dhëna për këtë periudhë',
    revenueByCategory: 'Të Ardhurat sipas Kategorisë',
    topPerformingCars: 'Makinat me Performancën më të Lartë',

    // ============ ADMIN BLOG ============
    blogPosts: 'Postimet e Blogut',
    newPost: 'Postim i Ri',
    title: 'Titulli',
    excerpt: 'Përshkrimi i Shkurtër',
    content: 'Përmbajtja',
    publishImmediately: 'Publiko menjëherë',
    editPost: 'Ndrysho Postimin',
    created: 'Krijuar',

    // ============ ADMIN MESSAGES ============
    messages: 'Mesazhet',
    noMessagesYet: 'Nuk ka mesazhe ende',
    noSubject: 'Pa subjekt',
    from: 'Nga',
    replyViaEmail: 'Përgjigju me Email',

    // ============ ADMIN SETTINGS ============
    settings: 'Cilësimet',
    saveChanges: 'Ruaj Ndryshimet',
    saved: 'U Ruajt',
    companyInfo: 'Informacioni i Kompanisë',
    companyName: 'Emri i Kompanisë',
    whatsappNumber: 'Numri i WhatsApp',
    address: 'Adresa',
    city: 'Qyteti',
    workingHoursTitle: 'Orari i Punës',
    weekdays: 'Ditë pune (Hën-Pre)',
    weekends: 'Fundjavë (Sht-Diel)',
    socialMedia: 'Rrjetet Sociale',
    facebookUrl: 'URL e Facebook',
    instagramUrl: 'URL e Instagram',
    tiktokUrl: 'URL e TikTok',

    // ============ ADMIN REVIEWS ============
    reviewsTitle: 'Vlerësimet',
    totalReviews: 'Vlerësime Totale',
    approved: 'E Aprovuar',
    rating: 'Vlerësimi',
    comment: 'Komenti',
    reviewDetails: 'Detajet e Vlerësimit',
    adminReply: 'Përgjigja e Adminit',
    repliedOn: 'Përgjigjur më',
    approve: 'Aprovo',
    reply: 'Përgjigju',
    editReply: 'Ndrysho Përgjigjen',
    deleteReview: 'Fshi Vlerësimin',
    deleteReviewConfirm: 'A jeni i sigurt që dëshironi të fshini këtë vlerësim? Ky veprim nuk mund të kthehet.',
    replyToReview: 'Përgjigju Vlerësimit',
    yourReply: 'Përgjigja Juaj',
    writeReply: 'Shkruani përgjigjen tuaj për këtë vlerësim...',
    sendReply: 'Dërgo Përgjigjen',

    // ============ ADMIN EXPENSES ============
    expenseTracking: 'Gjurmimi i Shpenzimeve',
    totalExpenses: 'Shpenzimet totale:',
    addExpense: 'Shto Shpenzim',
    allExpenses: 'Të Gjitha Shpenzimet',
    profitabilitySummary: 'Pasqyra e Përfitueshmërisë',
    noExpensesFound: 'Nuk u gjetën shpenzime',
    profitabilityNoData: 'Nuk ka të dhëna për përfitueshmërinë',
    expenses: 'Shpenzimet',
    profit: 'Fitimi',
    profitable: 'Fitimprurëse',
    loss: 'Humbje',
    editExpense: 'Ndrysho Shpenzimin',
    selectCar: 'Zgjidhni makinën',
    briefDescription: 'Përshkrim i shkurtër...',
    expenseDate: 'Data e Shpenzimit',
    vendor: 'Furnizuesi',
    vendorName: 'Emri i furnizuesit',
    receiptUrl: 'URL e Faturës',
    updateExpense: 'Përditëso Shpenzimin',
    deleteExpense: 'Fshi Shpenzimin',
    deleteExpenseConfirm: 'A jeni i sigurt që dëshironi të fshini këtë shpenzim? Ky veprim nuk mund të kthehet.',

    // ============ ADMIN MAINTENANCE ============
    maintenanceTitle: 'Planifikuesi i Mirëmbajtjes',
    newRecord: 'Regjistrim i Ri',
    alerts: 'Alarmet',
    records: 'Regjistrimet',
    types: 'Llojet',
    scheduled: 'E Planifikuar',
    inProgress: 'Në Progres',
    overdue: 'E Vonuar',
    scheduledDate: 'Data e Planifikuar',
    cost: 'Kostoja',
    markComplete: 'Shëno të Përfunduar',

    // ============ ADMIN PRICING ============
    dynamicPricing: 'Çmime Dinamike',
    lowDemand: 'Kërkesë e Ulët',
    mediumDemand: 'Kërkesë Mesatare',
    highDemand: 'Kërkesë e Lartë',
    veryHighDemand: 'Kërkesë Shumë e Lartë',
    demand: 'Kërkesa',
    advanceBooking: 'Rezervim Paraprak',
    durationLabel: 'Kohëzgjatja',
    lastMinute: 'Minutën e Fundit',
    event: 'Ngjarje',
    addRule: 'Shto Rregull',
    demandOverview: 'Pasqyra e Kërkesës',
    currentDemand: 'Kërkesa Aktuale',
    totalCarsCount: 'Makinat Totale',
    pricingRules: 'Rregullat e Çmimeve',
    noPricingRules: 'Nuk ka rregulla çmimesh të konfiguruara ende.',
    createFirstRule: 'Krijo Rregullin e Parë',
    priority: 'Prioriteti',
    conditions: 'Kushtet',
    priceCalculator: 'Kalkulatori i Çmimeve',
    selectCarLabel: 'Zgjidhni makinën',
    calculatePrice: 'Llogarit Çmimin',
    seasonalMultiplier: 'Shumëzuesi Sezonal',
    dynamicMultiplier: 'Shumëzuesi Dinamik',
    finalDailyRate: 'Tarifa Përfundimtare Ditore',
    totalDays: 'Ditët Totale',
    totalPrice: 'Çmimi Total',
    appliedRules: 'Rregullat e Aplikuara',

    // ============ ADMIN LOYALTY ============
    loyaltyProgram: 'Programi i Besnikërisë',
    totalMembers: 'Anëtarët Total',
    pointsIssued: 'Pikët e Lëshuara',
    bronze: 'Bronzi',
    silver: 'Argjendi',
    gold: 'Ari',
    platinum: 'Platini',
    members: 'Anëtarët',
    rewardsLabel: 'Shpërblimet',
    pointsBalance: 'Bilanci i Pikëve',
    lifetimePoints: 'Pikët Gjithsej',
    newReward: 'Shpërblim i Ri',
    rewardName: 'Emri i Shpërblimit',
    rewardType: 'Lloji i Shpërblimit',
    discountPercent: 'Zbritje %',
    fixedDiscount: 'Zbritje Fikse',
    freeDay: 'Ditë Falas',
    upgrade: 'Përmirësim',
    freeExtra: 'Shtesë Falas',
    pointsCost: 'Kostoja në Pikë',
    minimumTier: 'Niveli Minimal',
    adjustPoints: 'Rregullо Pikët',
    addPoints: 'Shto Pikë',
    bonus: 'Bonus',
    adjust: 'Rregullim',
    expire: 'Skadon',
    redeemReward: 'Shpërble Shpërblimin',
    selectReward: 'Zgjidhni Shpërblimin',
    redeem: 'Shpërble',
    pointsPerEuro: 'Pikë për Euro',
    tierThresholds: 'Kufijtë e Niveleve',
    saveSettings: 'Ruaj Cilësimet',

    // ============ ADMIN NOTIFICATIONS ============
    whatsappNotifications: 'Njoftimet WhatsApp',
    totalSent: 'Totali i Dërguara',
    delivered: 'E Dorëzuar',
    failed: 'Dështuar',
    notificationLog: 'Regjistri i Njoftime',
    templates: 'Shabllonet',
    sendManual: 'Dërgo Manualisht',
    recipient: 'Marrësi',
    reservationNum: 'Nr. Rezervimit',
    sentAt: 'Dërguar Më',
    noNotificationsFound: 'Nuk u gjetën njoftime',
    noTemplatesFound: 'Nuk u gjetën shabllone',
    editTemplate: 'Ndrysho Shabllonin',
    templateName: 'Emri i Shabllonit',
    templateBody: 'Trupi i Shabllonit',
    availableVariables: 'Variablat e Disponueshme',
    sendWhatsappNotification: 'Dërgo Njoftime WhatsApp',
    phoneNumber: 'Numri i Telefonit',
    notificationType: 'Lloji i Njoftimit',
    reservationId: 'ID e Rezervimit',
    optional: '(opsionale)',
    sendNotification: 'Dërgo Njoftimin',
    openWhatsapp: 'Hap WhatsApp',

    // ============ ADMIN DELIVERIES ============
    deliveryTracking: 'Gjurmimi i Dërgesave',
    assigned: 'E Caktuar',
    enRoute: 'Në Rrugë',
    arrived: 'E Arritur',
    driver: 'Shoferi',
    delivery: 'Dërgesa',
    returnPickup: 'Marrje Kthimi',
    destination: 'Destinacioni',
    noDeliveriesFound: 'Nuk u gjetën dërgesa',
    newDelivery: 'Dërgesë e Re',
    chatOnWhatsapp: 'Bisedo në WhatsApp',
    activeDeliveries: 'dërgesa aktive',
    createDelivery: 'Krijo Dërgesën',
    deliveryDetails: 'Detajet e Dërgesës',
    locationHistory: 'Historiku i Vendndodhjes',
    noLocationData: 'Nuk ka të dhëna vendndodhjeje ende.',
    loadingLocationsText: 'Duke ngarkuar vendndodhjet...',
    reservationIdLabel: 'ID e Rezervimit',
    enterReservationId: 'Shkruani ID e rezervimit',
    selectADriver: 'Zgjidhni një shofer',
    destinationAddress: 'Adresa e Destinacionit',
    fullDeliveryAddress: 'Adresa e plotë e dërgesës',
    latitude: 'Gjerësia gjeografike',
    longitude: 'Gjatësia gjeografike',
    specialInstructions: 'Udhëzime të veçanta...',
    notesLabel: 'Shënime',
    started: 'Filluar',

    // ============ ADMIN NEW RESERVATION ============
    newReservationTitle: 'Rezervim i Ri',
    fillRequiredFields: 'Ju lutem plotësoni të gjitha fushat e detyrueshme',
    fixPhoneNumber: 'Ju lutem korrigjoni numrin e telefonit',
    creating: 'Duke u krijuar...',
    createReservationInvoice: 'Krijo Rezervimin dhe Gjenero Faturën',
    customerDetails: 'Detajet e Klientit',
    vehicleLabel: 'Automjeti',
    datesLocations: 'Datat dhe Vendndodhjet',
    notesStatus: 'Shënimet dhe Statusi',
    adminNotesLabel: 'Shënimet e Adminit',
    internalNotes: 'Shënime interne...',
    initialStatus: 'Statusi Fillestar',
    priceSummary: 'Përmbledhja e Çmimit',

    // ============ ADMIN CALENDAR ============
    reservationCalendar: 'Kalendari i Rezervimeve',
    week: 'Java',
    month: 'Muaji',
    noReservationsDisplay: 'Nuk ka rezervime për të shfaqur',

    // ============ CAR FORM ============
    details: 'Detajet',
    pricing: 'Çmimet',
    imagesTab: 'Fotot',
    featuresTab: 'Veçoritë',
    brand: 'Marka',
    model: 'Modeli',
    year: 'Viti',
    economy: 'Ekonomike',
    compact: 'Kompakte',
    sedan: 'Sedan',
    suv: 'SUV',
    luxury: 'Luksoze',
    van: 'Furgon',
    sports: 'Sportive',
    petrol: 'Benzinë',
    diesel: 'Naftë',
    hybrid: 'Hibride',
    electric: 'Elektrike',
    manual: 'Manuale',
    automatic: 'Automatike',
    seats: 'Ulëset',
    doors: 'Dyert',
    horsepower: 'Kuaj-fuqi',
    engineCC: 'Motori CC',
    color: 'Ngjyra',
    licensePlate: 'Targa',
    mileageKm: 'Kilometrazhi (km)',
    pricePerDayEur: 'Çmimi për Ditë (EUR)',
    pricePerWeekEur: 'Çmimi për Javë (EUR)',
    depositEur: 'Depozita (EUR)',
    featuredCar: 'Makinë e veçantë (shfaqet në faqen kryesore)',
    saveCarFirst: 'Ruani makinën së pari, pastaj mund të shtoni foto.',
    addImageUrl: 'Shto URL të Fotos',
    addImage: 'Shto Foto',
    adding: 'Duke u shtuar...',
    pasteImageUrl: 'Ngjisni çdo URL fotoje. Fotoja e parë do të vendoset si foto kryesore.',
    primaryImage: 'Kryesore',
    noImagesYet: 'Nuk ka foto ende. Shtoni një më lart.',
    setAsPrimary: 'Vendos si kryesore',
    selectFeatures: 'Zgjidhni veçoritë që ka kjo makinë:',
    gps: 'GPS',
    airConditioning: 'Kondicioneri',
    bluetooth: 'Bluetooth',
    usb: 'USB',
    cruiseControl: 'Kontroll Lundrimi',
    parkingSensors: 'Sensorë Parkimi',
    backupCamera: 'Kamerë Parkimi',
    heatedSeats: 'Ulëse me Ngrohje',
    leatherSeats: 'Ulëse Lëkure',
    sunroof: 'Çati Diellore',
    appleCarplay: 'Apple CarPlay',
    androidAuto: 'Android Auto',
    keylessEntry: 'Hyrje pa Çelës',
    abs: 'ABS',
    airbags: 'Ajrbeg',
    updateCar: 'Përditëso Makinën',
    createCar: 'Krijo Makinën',
    addNewCarTitle: 'Shto Makinë të Re',
    editCarTitle: 'Ndrysho Makinën',
  },
} as const;

type Translations = { [K in keyof typeof translations.en]: string };

interface LanguageStore {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Translations;
}

export const useLanguageStore = create<LanguageStore>()(
  persist(
    (set, get) => ({
      lang: 'en',
      setLang: (lang: Lang) => set({ lang, t: translations[lang] }),
      t: translations.en,
    }),
    {
      name: 'nexora-language',
      onRehydrateStorage: () => (state) => {
        if (state) {
          state.t = translations[state.lang];
        }
      },
    }
  )
);
